// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import '../../model/merit/merit.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5569934779932106919),
    name: 'MeritEntity',
    lastPropertyId: const obx_int.IdUid(7, 7985472910228302918),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6762251251760336055),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8339180912444427235),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4527913469264388143),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 888508973278993105),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6881104067872311289),
        name: 'meritTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7985472910228302918),
        name: 'recipient',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5569934779932106919),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [4444448841942027272],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MeritEntity: obx_int.EntityDefinition<MeritEntity>(
      model: _entities[0],
      toOneRelations: (MeritEntity object) => [],
      toManyRelations: (MeritEntity object) => {},
      getId: (MeritEntity object) => object.id,
      setId: (MeritEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MeritEntity object, fb.Builder fbb) {
        final nameOffset =
            object.name == null ? null : fbb.writeString(object.name!);
        final descriptionOffset =
            object.description == null
                ? null
                : fbb.writeString(object.description!);
        final recipientOffset =
            object.recipient == null
                ? null
                : fbb.writeString(object.recipient!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.createdAt);
        fbb.addInt64(5, object.meritTypeIndex);
        fbb.addOffset(6, recipientOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final meritTypeIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final recipientParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = MeritEntity(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          createdAt: createdAtParam,
          meritTypeIndex: meritTypeIndexParam,
          recipient: recipientParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MeritEntity] entity fields to define ObjectBox queries.
class MeritEntity_ {
  /// See [MeritEntity.id].
  static final id = obx.QueryIntegerProperty<MeritEntity>(
    _entities[0].properties[0],
  );

  /// See [MeritEntity.name].
  static final name = obx.QueryStringProperty<MeritEntity>(
    _entities[0].properties[1],
  );

  /// See [MeritEntity.description].
  static final description = obx.QueryStringProperty<MeritEntity>(
    _entities[0].properties[2],
  );

  /// See [MeritEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<MeritEntity>(
    _entities[0].properties[3],
  );

  /// See [MeritEntity.meritTypeIndex].
  static final meritTypeIndex = obx.QueryIntegerProperty<MeritEntity>(
    _entities[0].properties[4],
  );

  /// See [MeritEntity.recipient].
  static final recipient = obx.QueryStringProperty<MeritEntity>(
    _entities[0].properties[5],
  );
}
